### ISSUE TITLE
Reading position gets lost after rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [mannd/epmobile#35]
Reading position of Para-Hisian Pacing gets lost after screen orientation changes.

![Screen Shot 2020-08-05 at 9 00 18 PM](https://user-images.githubusercontent.com/67744580/89415779-f5dcb000-d75e-11ea-880e-4bec394f73c1.png)
![Screen Shot 2020-08-05 at 9 00 25 PM](https://user-images.githubusercontent.com/67744580/89415791-f9703700-d75e-11ea-84f8-8402526a97fe.png)

**Comment by mannd** [comment]
With Android the view gets reloaded with device rotation.  It would be possible to store some kind of page offset position to place the view back to its saved position, but I didn't think it was worth the effort.  Do you think it is important?  A flip of the finger gets you back to where you were.  Note that this potentially affects all scrollable views in the app.

**Comment by mannd** [comment]
Note to self: possible solution to this issue here: https://stackoverflow.com/questions/6855715/maintain-webview-content-scroll-position-on-orientation-change

**Comment by mannd** [comment]
Fixed in commit 9a02cff.  Will upload fix to Play store.
