### ISSUE TITLE
Reading position lost after device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [mannd/epmobile#37]
Steps to reproduce (An example):
1. Open "RV Apex vs Base Pacing" and scroll the page
![Screen Shot 2021-04-14 at 8 58 47 PM](https://user-images.githubusercontent.com/67744580/114714163-6c0cca00-9d64-11eb-9f10-b242a1696e56.png)

2. Rotate device
![Screen Shot 2021-04-14 at 8 58 56 PM](https://user-images.githubusercontent.com/67744580/114714144-6911d980-9d64-11eb-8691-0b89fea1983d.png)

Reading position then gets lost. Users have to manually restore the reading position.

**Comment by mannd** [comment]
Thanks, will fix...

**Comment by mannd** [comment]
It looks like the rotation position preservation code was removed in commit [#16607c](https://github.com/mannd/epmobile/commit/16607c6eb19d379fa28f81df05317c1bf1a1349b) because of deprecation of some of the methods used.  Will restore.

**Comment by mannd** [comment]
Fixed in commit #ff5345c.
