### ISSUE TITLE
Display Issues in under larger scaling settings 

### ISSUE THREAD

**Issue by gaosher** [mannd/epmobile#42]
hey,
thanks for your effort for developing this awsome app! in the process of using epmobile, i found some adaptive display bugs under largest font size and largest display size.
Screen shots:
these two buttons can't be displayed completely.
![0_incomplete](https://github.com/user-attachments/assets/17ceb254-634a-4572-99d1-b315cad8c800)
i belive the buggy views are Button @id/risk_scores_button, @id/diagnosis_button  in mainscreen.xml .
hope this info will help to locate and fix the bug :)

app version: 2.34.0
device: Pixel 2
Android version: 10.0
screen resolution: 1920 * 1080

**Comment by mannd** [comment]
Thanks for bringing the to my attention.  Will correct issue.

**Comment by mannd** [comment]
Fixed in f30aeb3.
